#!/usr/bin/python
#
# Basic settings for Music Processor for Ticket to Atlantis LARP.
#

RESERVED_WEIGHT = 0
LOCATION_WEIGHT = 40
FOREST_WEIGHT = 40
CHARACTER_WEIGHT = 80
INTENTION_WEIGHT = 120
ADDICTION_WEIGHT = 160
MIST_WEIGHT = 200
MASTERKA_WEIGHT = 240
DEATH_WEIGHT = 280

MAX_ID = 300

LOCATION_ID_START = 1
LOCATION_ID_END = 20
LOCATION_IDS = xrange(LOCATION_ID_START, LOCATION_ID_END + 1)

FOREST_ID_START = 21
FOREST_ID_END = 89
FOREST_ALL_ID_END = (FOREST_ID_START + FOREST_ID_END) // 2
FOREST_IDS = xrange(FOREST_ID_START, FOREST_ID_END + 1)

MIST_ID_START = 90
MIST_ID_END = 100
MIST_IDS = xrange(MIST_ID_START, MIST_ID_END + 1)

CHARACTER_ID_START = 101
CHARACTER_ID_END = 179
CHARACTER_IDS = xrange(CHARACTER_ID_START, CHARACTER_ID_END + 1)

INTENTION_ID_START = 180
INTENTION_ID_END = 199
INTENTION_IDS = xrange(INTENTION_ID_START, INTENTION_ID_END + 1)

EMOTION_FIX_ID_START = 200
EMOTION_FIX_ID_END = 299
EMOTION_FIX_IDS = xrange(EMOTION_FIX_ID_START, EMOTION_FIX_ID_END + 1)

assert 0 < LOCATION_ID_START < LOCATION_ID_END < FOREST_ID_START < FOREST_ID_END < MIST_ID_START < MIST_ID_END < CHARACTER_ID_START < CHARACTER_ID_END < INTENTION_ID_START < INTENTION_ID_END < EMOTION_FIX_ID_START < EMOTION_FIX_ID_END < MAX_ID
