#!/usr/bin/python
#
# Basic settings for Music Processor for Ticket to Atlantis LARP.
#

RESERVED_WEIGHT = 0
LOCATION_WEIGHT = 40
FOREST_WEIGHT = 40
CHARACTER_WEIGHT = 80
INTENTION_WEIGHT = 120
ADDICTION_WEIGHT = 160
MIST_WEIGHT = 200
MASTERKA_WEIGHT = 240
DEATH_WEIGHT = 280

MAX_ID = 349

MASTER_ID_START = 1
MASTER_ID_END = 6
MASTER_IDS = xrange(MASTER_ID_START, MASTER_ID_END + 1)

MOB_ID_START = 7
MOB_ID_END = 10
MOB_IDS = xrange(MOB_ID_START, MOB_ID_END + 1)

PLACEHOLDER_ID_START = 11
PLACEHOLDER_ID_END = 40
PLACEHOLDER_IDS = xrange(PLACEHOLDER_ID_START, PLACEHOLDER_ID_END + 1)

LOCATION_ID_START = 41
LOCATION_ID_END = 47
LOCATION_IDS = xrange(LOCATION_ID_START, LOCATION_ID_END + 1)

FORESTA_ID_START = 48
FORESTA_ID_END = 99
FORESTA_IDS = xrange(FORESTA_ID_START, FORESTA_ID_END + 1)

EMOTION_FIX_ID_START = 100
EMOTION_FIX_ID_END = 190
EMOTION_FIX_IDS = xrange(EMOTION_FIX_ID_START, EMOTION_FIX_ID_END + 1)

LODGE_ID_START = 191
LODGE_ID_END = 200
LODGE_IDS = xrange(LODGE_ID_START, LODGE_ID_END + 1)

CHARACTER_ID_START = 201
CHARACTER_ID_END = 279
CHARACTER_IDS = xrange(CHARACTER_ID_START, CHARACTER_ID_END + 1)

FORESTBC_ID_START = 280
FORESTBC_ID_END = 319
FORESTBC_IDS = xrange(FORESTBC_ID_START, FORESTBC_ID_END + 1)

MIST_ID_START = 320
MIST_ID_END = 329
MIST_IDS = xrange(MIST_ID_START, MIST_ID_END + 1)

INTENTION_ID_START = 330
INTENTION_ID_END = 349
INTENTION_IDS = xrange(INTENTION_ID_START, INTENTION_ID_END + 1)

assert 0 < MASTER_ID_START < MASTER_ID_END < MOB_ID_START < MOB_ID_END \
		 < PLACEHOLDER_ID_START < PLACEHOLDER_ID_END < LOCATION_ID_START < LOCATION_ID_END \
		 < FORESTA_ID_START < FORESTA_ID_END < EMOTION_FIX_ID_START < EMOTION_FIX_ID_END \
		 < LODGE_ID_START < LODGE_ID_END < CHARACTER_ID_START < CHARACTER_ID_END \
		 < FORESTBC_ID_START < FORESTBC_ID_END < MIST_ID_START < MIST_ID_END \
		 < INTENTION_ID_START < INTENTION_ID_END <= MAX_ID
