#!/usr/bin/python
#
# Basic settings for Music Processor for Ticket to Atlantis LARP.
#

LOCATION_ID_START = 1
LOCATIONS_ID_END = 89
LOCATION_IDS = xrange(LOCATION_ID_START, LOCATIONS_ID_END + 1)

MIST_ID_START = 90
MIST_ID_END = 99
MIST_IDS = xrange(MIST_ID_START, MIST_ID_END + 1)

CHARACTER_ID_START = 101
CHARACTER_ID_END = 189
CHARACTER_IDS = xrange(CHARACTER_ID_START, CHARACTER_ID_END + 1)

INTENTION_ID_START = 190
INTENTION_ID_END = 209
INTENTION_IDS = xrange(INTENTION_ID_START, INTENTION_ID_END + 1)

EMOTION_FIX_ID_START = 210
EMOTION_FIX_ID_END = 299
EMOTION_FIX_IDS = xrange(EMOTION_FIX_ID_START, EMOTION_FIX_ID_END + 1)

assert 0 < LOCATION_ID_START < LOCATIONS_ID_END < MIST_ID_START < MIST_ID_END < CHARACTER_ID_START < CHARACTER_ID_END < INTENTION_ID_START < INTENTION_ID_END < EMOTION_FIX_ID_START < EMOTION_FIX_ID_END < 2 ** 15
