#!/usr/bin/python
#
# Basic settings for Red Arrow Mesh Demonstration.
#
LOCATION_ID_START = 1
LOCATION_ID_END = 47
LOCATION_IDS = xrange(LOCATION_ID_START, LOCATION_ID_END + 1)

PLACEHOLDER_ID_START = 48
PLACEHOLDER_ID_END = 99
PLACEHOLDER_IDS = xrange(PLACEHOLDER_ID_START, PLACEHOLDER_ID_END + 1)

FOREST_ID_START = 150
FOREST_ID_END = 199
FOREST_IDS = xrange(FOREST_ID_START, FOREST_ID_END + 1)

PERSON_ID_START = 201
PERSON_ID_END = 299
PERSON_IDS = xrange(PERSON_ID_START, PERSON_ID_END + 1)

MAX_ID = MAX_MESH_ID = 299

assert 0 < LOCATION_ID_START < LOCATION_ID_END < PLACEHOLDER_ID_START < PLACEHOLDER_ID_END < FOREST_ID_START < FOREST_ID_END < PERSON_ID_START < PERSON_ID_END <= MAX_ID
