#!/usr/bin/python
#
# Basic settings for Red Arrow Mesh Demonstration.
#
MASTER_ID_START = 1
MASTER_ID_END = 9
MASTER_IDS = xrange(MASTER_ID_START, MASTER_ID_END + 1)

PLACEHOLDER_ID_START = 10
PLACEHOLDER_ID_END = 49
PLACEHOLDER_IDS = xrange(PLACEHOLDER_ID_START, PLACEHOLDER_ID_END + 1)

LOCATION_ID_START = 50
LOCATION_ID_END = 99
LOCATION_IDS = xrange(LOCATION_ID_START, LOCATION_ID_END + 1)

FOREST_ID_START = 100
FOREST_ID_END = 199
FOREST_IDS = xrange(FOREST_ID_START, FOREST_ID_END + 1)

PERSON_ID_START = 200
PERSON_ID_END = 299
PERSON_IDS = xrange(PERSON_ID_START, PERSON_ID_END + 1)

MAX_ID = MAX_MESH_ID = 299

assert 0 < MASTER_ID_START < MASTER_ID_END < PLACEHOLDER_ID_START < PLACEHOLDER_ID_END < LOCATION_ID_START < LOCATION_ID_END < FOREST_ID_START < FOREST_ID_END < PERSON_ID_START < PERSON_ID_END <= MAX_ID
